/**
 * Generated by scripts/blender/build_saurians.py — do not hand-edit.
 * Re-export: blender --background --python scripts/blender/build_saurians.py
 */
import type { BodyId, LegId } from "./types";

export const SAURIAN_KIT_URL = "/models/saurian-kit.glb";

export type KitSockets = {
  stance: "biped" | "quad";
  pitch: number;
  hip: { x: number; z: number };
  shoulder: { x: number; z: number };
  jaw: [number, number, number];
  eye: { x: number; y: number; z: number };
  brow: { x: number; y: number; z: number };
  arm: { position: [number, number, number]; rotation: [number, number, number] };
  tailRoot: {
    position: [number, number, number];
    rotation: [number, number, number];
  };
  accessory: [number, number, number];
  tailLength: number;
};

export const KIT_SOCKETS: Record<BodyId, KitSockets> = {
  sleek: {
    stance: "biped",
    pitch: -0.050,
    hip: { x: 0.170, z: -0.100 },
    shoulder: { x: 0.230, z: 0.500 },
    jaw: [0.000, 0.460, 1.360],
    eye: { x: 0.155, y: 0.620, z: 1.160 },
    brow: { x: 0.090, y: 0.700, z: 1.060 },
    arm: {
      position: [0.230, 0.240, 0.500],
      rotation: [0.820, 0.000, 0.820],
    },
    tailRoot: {
      position: [0.000, 0.160, -0.460],
      rotation: [-0.100, 0.000, 0.000],
    },
    accessory: [0.000, 0.580, 0.180],
    tailLength: 1.320,
  },
  plump: {
    stance: "quad",
    pitch: 0.020,
    hip: { x: 0.300, z: -0.400 },
    shoulder: { x: 0.300, z: 0.540 },
    jaw: [0.000, 0.660, 2.640],
    eye: { x: 0.110, y: 0.800, z: 2.500 },
    brow: { x: 0.080, y: 0.860, z: 2.400 },
    arm: {
      position: [0.420, 0.200, 0.520],
      rotation: [0.100, 0.000, 0.280],
    },
    tailRoot: {
      position: [0.000, 0.180, -0.700],
      rotation: [-0.200, 0.000, 0.000],
    },
    accessory: [0.000, 0.580, 0.160],
    tailLength: 1.620,
  },
  spiky: {
    stance: "quad",
    pitch: 0.030,
    hip: { x: 0.320, z: -0.400 },
    shoulder: { x: 0.300, z: 0.500 },
    jaw: [0.000, 0.200, 1.660],
    eye: { x: 0.095, y: 0.320, z: 1.480 },
    brow: { x: 0.070, y: 0.380, z: 1.360 },
    arm: {
      position: [0.380, 0.160, 0.460],
      rotation: [0.080, 0.000, 0.200],
    },
    tailRoot: {
      position: [0.000, 0.160, -0.800],
      rotation: [-0.120, 0.000, 0.000],
    },
    accessory: [0.000, 0.520, 0.080],
    tailLength: 1.520,
  },
};

export const LEG_DROP: Record<LegId, number> = {
  stubby: 0.560,
  stilts: 0.940,
  paddles: 0.540,
};
