/**
 * Generated by scripts/blender/build_saurians.py — do not hand-edit.
 * Re-export: blender --background --python scripts/blender/build_saurians.py
 */
import type { BodyId, LegId } from "./types";

export const SAURIAN_KIT_URL = "/models/saurian-kit.glb";

export type KitSockets = {
  stance: "biped" | "quad";
  pitch: number;
  hip: { x: number; z: number };
  shoulder: { x: number; z: number };
  jaw: [number, number, number];
  eye: { x: number; y: number; z: number };
  brow: { x: number; y: number; z: number };
  arm: { position: [number, number, number]; rotation: [number, number, number] };
  tailRoot: {
    position: [number, number, number];
    rotation: [number, number, number];
  };
  accessory: [number, number, number];
  tailLength: number;
};

export const KIT_SOCKETS: Record<BodyId, KitSockets> = {
  sleek: {
    stance: "biped",
    pitch: -0.040,
    hip: { x: 0.190, z: -0.080 },
    shoulder: { x: 0.260, z: 0.580 },
    jaw: [0.000, 0.340, 1.500],
    eye: { x: 0.175, y: 0.500, z: 1.270 },
    brow: { x: 0.100, y: 0.600, z: 1.160 },
    arm: {
      position: [0.260, 0.180, 0.580],
      rotation: [0.850, 0.000, 0.850],
    },
    tailRoot: {
      position: [0.000, 0.120, -0.520],
      rotation: [-0.160, 0.000, 0.000],
    },
    accessory: [0.000, 0.520, 0.220],
    tailLength: 1.420,
  },
  plump: {
    stance: "quad",
    pitch: 0.020,
    hip: { x: 0.320, z: -0.420 },
    shoulder: { x: 0.300, z: 0.520 },
    jaw: [0.000, 0.480, 2.720],
    eye: { x: 0.120, y: 0.620, z: 2.520 },
    brow: { x: 0.080, y: 0.680, z: 2.400 },
    arm: {
      position: [0.440, 0.180, 0.500],
      rotation: [0.120, 0.000, 0.320],
    },
    tailRoot: {
      position: [0.000, 0.160, -0.720],
      rotation: [-0.220, 0.000, 0.000],
    },
    accessory: [0.000, 0.540, 0.180],
    tailLength: 1.600,
  },
  spiky: {
    stance: "quad",
    pitch: 0.030,
    hip: { x: 0.340, z: -0.420 },
    shoulder: { x: 0.300, z: 0.480 },
    jaw: [0.000, 0.180, 1.800],
    eye: { x: 0.100, y: 0.300, z: 1.560 },
    brow: { x: 0.070, y: 0.360, z: 1.420 },
    arm: {
      position: [0.400, 0.140, 0.420],
      rotation: [0.080, 0.000, 0.220],
    },
    tailRoot: {
      position: [0.000, 0.160, -0.780],
      rotation: [-0.120, 0.000, 0.000],
    },
    accessory: [0.000, 0.480, 0.100],
    tailLength: 1.500,
  },
};

export const LEG_DROP: Record<LegId, number> = {
  stubby: 0.560,
  stilts: 0.940,
  paddles: 0.540,
};
